Feature/upgrade db
nautible/nautible-infra pull request #67
Opened 2024-06-11 07:42 UTC by ogis-yamanaka

KeycloakのPostgres、商品DBのMySQL、セッション用のElastiCashのバージョンアップ

2024-06-11 22:36 UTC, SaitoMunenori requested changes

2024-06-11 22:36 UTC, SaitoMunenori commented on aws/app-ms/env/dev/variables.tf
> +variable "productdb" {
productdb⇒productの方がより良いと思います。ご検討ください。

2024-06-11 22:36 UTC, SaitoMunenori commented on aws/app-ms/env/dev/variables.tf
> +    parameter_group = object({
こちらは、mysqlの配下に引っ越すと上記修正と整合性が取れると思いました。

2024-06-12 00:13 UTC, ogis-yamanaka commented on aws/app-ms/env/dev/variables.tf
> +variable "productdb" {
productに修正しました。

2024-06-12 00:13 UTC, ogis-yamanaka commented on aws/app-ms/env/dev/variables.tf
> +    parameter_group = object({
parameter_groupをmysql配下に移動いたしました。

2024-06-12 00:23 UTC, SaitoMunenori approved these changes

2024-06-12 00:23 UTC, merged